### ISSUE TITLE
English Translation: Port Salwater mistranslation?

### ISSUE THREAD

**Issue by toruzz** [rparnas/frogslator#6]
I think that Port Salwater (港町シーミズ) is a mistranslation as the Katakana reads "Shi-mizu" (or Seamist), and looking at the translation notes I can see this went unnoticed.
So probably **Port Seamist** would be a better translation.
For reference, I noticed it because of how they call it here: http://strategywiki.org/wiki/Kaeru_no_Tame_ni_Kane_wa_Naru/Areas

Also, and just as a note (as I really like the Hop Hop Springs name), I think that the Gerobeppu meaning also went unnoticed. Gero = Croak and Beppu is a city known for its hot springs.
Anyway, Hop Hop Springs is probably better than Croakjavík or something like that.

**Comment by rparnas** [comment]
These are deliberate localizations.

We localized みなと町 シーミ (Port Town Shimizu) to Saltwater to remove the pun which references the actual port Shimizu (meaning Purewater or Clearwater) and to add another snack related pun.

We localized ゲロベップおんせん (Gerobepp) to Hop Hop Springs to remove the pun which references the town Beppu as well as changing croak to hop for variety and as croak isn't pleasant or cute sounding in English.
